#mybatis-plus:
#  global-config:
#    db-config:
#      table-prefix: jk_
#mybatis:
#  type-aliases-package: com.jktime.framework.entity
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml